version: '3.7'
services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uploaddb
    logging:
        options:
          max-size: 10m
          max-file: "3"
    volumes:
      - './database/volume/bk:/bk'
      - './database/volume/data:/var/lib/postgresql/data'
    networks:
      - network-upload
networks:
  network-upload:
    driver: bridge
