version: '3.7'

services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - 4321:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uploaddb
    logging:
        options:
          max-size: 10m
          max-file: "3"
    volumes:
      - './packages/database/volume/bk:/bk'
      - './packages/database/volume/data:/var/lib/postgresql/data'
    networks:
      - network-upload
  app:
    build:
      context: packages/client
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - server
    links:
      - server
  server:
    build:
      context: packages/server
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/server/
      - /usr/src/server/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - database
    links:
      - database
networks:
  network-upload:
    driver: bridge
